In [1]:
import numpy as np


## numpy arrays

In [2]:
MyList = [1,2,3,4]

In [3]:
type(MyList)

list

In [5]:
np.array(MyList)

array([1, 2, 3, 4])

In [6]:
matrixList=[[1,2,3],[3,4,5],[6,7,8]]

In [7]:
np.array(matrixList) ## iki boyutlu listelememizi sağladı

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

## arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace 

In [25]:

np.linspace(0,20,12)  ##aralıkları eşit tutarak istenilen sayı kadar veriyi sıralıyor


array([ 0.        ,  1.81818182,  3.63636364,  5.45454545,  7.27272727,
        9.09090909, 10.90909091, 12.72727273, 14.54545455, 16.36363636,
       18.18181818, 20.        ])

## eye

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(10) ##diagonal birim matris veriyor

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [35]:
np.random.randn(5)

array([ 0.20200821, -1.21830964,  0.89561286, -1.16243323,  0.0576113 ])

In [84]:

np.random.randint(1,300,5)

array([ 14, 146,  25, 158, 121])

In [105]:
MynpList= np.arange(30)

In [106]:
MynpList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
MyrnpList = np.random.randint(1,10,5)

In [91]:
MyrnpList

array([8, 2, 5, 8, 9])

## numpy dizi methodları

In [113]:
MynpList.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])