In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]  ##listelerle aynı


5

In [7]:
benimDizim [3:5]  ##verilen aralıktaki verileri veriyor stop indexi dahil değil

array([3, 4])

In [10]:
benimDizim[3:8]=-5  ## 3 ila 8 arasını - 5 yapan komut stop indexi unutma

In [11]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [12]:
baskaDizi = np.arange(0,24)

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicingDizi= baskaDizi[4:9]

In [20]:
slicingDizi

array([4, 5, 6, 7, 8])

In [21]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
slicingDizi[:]=700

In [25]:
slicingDizi

array([700, 700, 700, 700, 700])

In [26]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi = np.arange(0,24)

In [28]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
ornekDiziKopyasi = ornekDizi.copy()

In [30]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [34]:
ornekDiziKopyaSlicing [:]=800

In [35]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [36]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:

ornekDiziKopyasi


array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## matrix

In [53]:
benimListem = [[10,20,30],[40,5,87],[9,7,6]]

In [54]:
benimMatrixDizim = np.array(benimListem)

In [55]:
benimMatrixDizim

array([[10, 20, 30],
       [40,  5, 87],
       [ 9,  7,  6]])

In [56]:
benimMatrixDizim[2,2]

6

In [57]:
benimMatrixDizim[2][2]

6

In [64]:
benimMatrixDizim[1:,2]  ##1den 2 ye kadar olan rowların ikinci indeksine kadar veriyi çeker

array([87,  6])

In [65]:
yeniListw = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

In [66]:
yeniMatrix = np.array(yeniListw)

In [67]:
yeniMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [75]:
yeniMatrix[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

## operasyonlar

In [80]:
yeniBirDizi = np.random.randint(1,100,20)

In [81]:
yeniBirDizi

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93,  4, 36, 90, 65, 69, 17,
       59, 33, 88])

In [83]:
yeniBirDizi > 24  ##boolean olarka döndürdü güzel komut!!!!

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True])

In [84]:
yeniBirDizi

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93,  4, 36, 90, 65, 69, 17,
       59, 33, 88])

In [85]:
sonucDizisi = yeniBirDizi > 24

In [86]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True])

In [87]:
yeniBirDizi

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93,  4, 36, 90, 65, 69, 17,
       59, 33, 88])

In [88]:
yeniBirDizi[sonucDizisi]  ##24ten büyük rakamları filtreledi false truel almadı ÇOK GÜZEL OLAY!!!!

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93, 36, 90, 65, 69, 59, 33,
       88])

In [89]:
yeniBirDizi

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93,  4, 36, 90, 65, 69, 17,
       59, 33, 88])

In [90]:
yeniBirDizi[yeniBirDizi>24] ##yine aynı kod olmuş oldu!!! dizi filtreledik çok iyi

array([87, 62, 99, 82, 57, 84, 47, 48, 36, 82, 93, 36, 90, 65, 69, 59, 33,
       88])

In [91]:
sonDizi = np.arange(0,24)

In [93]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [94]:
sonDizi + sonDizi  ## iki dizi elemanlarını topladı

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [95]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [96]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [97]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [98]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [99]:
np.max(sonDizi)

23

In [100]:
np.min(sonDizi)

0